---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-admin
rules:
- apiGroups: [""]
  resources: ["persistentvolumes", "storageclasses"]
  verbs: ["get", "watch", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: michelle-storage-admin
subjects:
- kind: User
  name: michelle
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: storage-admin
  apiGroup: rbac.authorization.k8s.io

# test this ClusterRoleBinding using "kubectl can-i":
# 
# kubectl auth can-i create pv --as michelle
# Warning: resource 'persistentvolumes' is not namespace scoped
# yes
# 
# kubectl auth can-i delete pv --as michelle
# Warning: resource 'persistentvolumes' is not namespace scoped
# yes